services:
  icecast:
    image: moul/icecast
    container_name: icecast
    restart: always
    ports:
      - 8010:8000
    environment:
      - ICECAST_SOURCE_PASSWORD=Uc$*$2DkRKN1q12#acWq&HvfbKU#FV
      - ICECAST_ADMIN_PASSWORD=Uc$*$2DkRKN1q12#acWq&HvfbKU#FV
      - ICECAST_PASSWORD=Uc$*$2DkRKN1q12#acWq&HvfbKU#FV
      - ICECAST_RELAY_PASSWORD=Uc$*$2DkRKN1q12#acWq&HvfbKU#FV

  liquidsoap:
    image: savonet/liquidsoap:rolling-release-v2.2.x
    container_name: liquidsoap
    restart: always
    command: ["/radio.liq"]
    user: "1000:1000"
    ports:
      - 7001:7001
    depends_on:
      - icecast
    volumes:
      - /music:/music
      - /home/subasically/appdata/radio_masina/radio.liq:/radio.liq

  radio_masina:
    image: ghcr.io/subasically/radio_masina:latest
    container_name: radio_masina
    restart: always
    depends_on:
      - icecast
      - liquidsoap
    volumes:
      - /music:/music
      - /mnt/storage/data/appdata/radio_masina:/appdata
    environment:
      - OPENAI_API_KEY=
      - OPENAI_CHAT_API_URL=https://api.openai.com/v1/chat/completions
      - OPENAI_TTS_API_URL=https://api.openai.com/v1/audio/speech
      - OPENAI_VOICE=nova
      - ICECAST_HOST=icecast
      - ICECAST_PORT=8000
      - ICECAST_USER=AI_RADIO_MASINA
      - ICECAST_PASSWORD=Uc$*$2DkRKN1q12#acWq&HvfbKU#FV
      - ICECAST_MOUNT=/radio
      - RADIO_NAME=Basic Radio
      - DJ_NAME=DJ Mašina
      - MUSIC_DIR=
      - INTRO_SONG_PATH=/intros/intro_song.mp3
      - DJ_DEMEANOR=Fun and Energetic
      - DJ_GENDER=Female
      - DJ_LANGUAGE=Bosnian
    networks:
      - basic-network

networks:
  basic-network:
    external: true
