services:
  icecast:
    image: moul/icecast
    container_name: radio_masina_icecast
    restart: on-failure
    ports:
      - 8000:8000
    environment:
      - TZ=America/Chicago
      - ICECAST_SOURCE_PASSWORD=hackme
      - ICECAST_ADMIN_PASSWORD=hackme
      - ICECAST_PASSWORD=hackme
      - ICECAST_RELAY_PASSWORD=hackme
    networks:
      - basic-network

  liquidsoap:
    image: savonet/liquidsoap:v2.2.5 #savonet/liquidsoap:rolling-release-v2.3.x 
    container_name: radio_masina_liquidsoap
    restart: on-failure
    command: ["/radio_basic_no_ai.liq"]
    user: "1000:1000"
    ports:
      - 7001:7001
    environment:
      - TZ=America/Chicago
      - ICECAST_PASSWORD=hackme
      - ICECAST_HOST=icecast
      - ICECAST_PORT=8000
      - ICECAST_MOUNT=radio
      - LIQUIDSOAP_PORT=7001
    depends_on:
      - icecast
    volumes:
      - ./music:/music
      - ./radio_basic_no_ai.liq:/radio_basic_no_ai.liq
      - ./jingles:/jingles
      - ./intros:/intros
    networks:
      - basic-network

networks:
  basic-network:
    driver: bridge