services:
  icecast:
    image: moul/icecast
    container_name: radio_masina_icecast
    restart: always
    ports:
      - 8000:8000
    environment:
      - ICECAST_SOURCE_PASSWORD=changeme
      - ICECAST_ADMIN_PASSWORD=changeme
      - ICECAST_PASSWORD=changeme
      - ICECAST_RELAY_PASSWORD=changeme

  liquidsoap:
    image: savonet/liquidsoap:rolling-release-v2.2.x
    container_name: radio_masina_liquidsoap
    restart: always
    command: ["/radio.liq"]
    user: "1000:1000"
    ports:
      - 7001:7001
    environment:
      - ICECAST_PASSWORD=changeme
      - ICECAST_HOST=icecast
    depends_on:
      - icecast
    volumes:
      - /music:/music
      - /home/subasically/appdata/radio_masina/radio.liq:/radio.liq

  radio_masina_app:
    build: .
    container_name: radio_masina_app
    restart: always
    depends_on:
      - icecast
      - liquidsoap
    volumes:
      - /music:/music
      - /mnt/storage/data/appdata/radio_masina:/appdata
    environment:
      - OPENAI_API_KEY=
      - OPENAI_CHAT_API_URL=https://api.openai.com/v1/chat/completions
      - OPENAI_TTS_API_URL=https://api.openai.com/v1/audio/speech
      - OPENAI_VOICE=nova
      - ICECAST_HOST=icecast
      - ICECAST_PORT=8000
      - ICECAST_USER=AI_RADIO_MASINA
      - ICECAST_PASSWORD=changeme
      - ICECAST_MOUNT=radio # No leading slash
      - LIQUIDSOAP_HOST=liquidsoap
      - LIQUIDSOAP_PORT=7001
      - RADIO_NAME=Basic Radio
      - DJ_NAME=DJ Mašina
      - MUSIC_DIR=/mnt/storage/data/media/music/Radio
      - JINGLES_DIR=/mnt/storage/data/media/music/Radio/Chimes/chime.mp3
      - INTROS_DIR=/mnt/storage/data/media/music/Radio/Intros/intro_song.mp3
      - DJ_DEMEANOR=Fun and Energetic
      - DJ_GENDER=Female
      - DJ_LANGUAGE=Bosnian
    networks:
      - basic-network

networks:
  basic-network:
    external: true
