services:
  liquidsoap:
    image: savonet/liquidsoap:v2.2.5
    container_name: radio_masina_liquidsoap
    restart: on-failure
    command: ["/radio.liq"]
    user: "1000:1000"
    ports:
      - 7001:7001
    environment:
      - TZ=America/Chicago
      - ICECAST_PASSWORD=hackme
      - ICECAST_HOST=icecast
      - ICECAST_PORT=8000
      - ICECAST_MOUNT=radio
      - LIQUIDSOAP_PORT=7001
    volumes:
      - ./music:/music
      - ./radio.liq:/radio.liq
      - ./jingles:/jingles
      - ./intros:/intros
    networks:
      - basic-network

  file_watcher:
    build:
      context: .
      dockerfile: Dockerfile.file_watcher
    container_name: radio_masina_file_watcher
    restart: always
    volumes:
      - ./radio.liq:/radio.liq
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - liquidsoap
    networks:
      - basic-network

networks:
  basic-network:
    driver: bridge